/// Flutter icons CustomBar
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomBar
///      fonts:
///       - asset: fonts/CustomBar.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomBar {
  CustomBar._();

  static const _kFontFam = 'CustomBar';

  static const IconData home_run = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData bar_chart = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe802, fontFamily: _kFontFam);
}
